CREATE DATABASE LAB3_FARMACIE
GO

USE LAB3_FARMACIE
GO

CREATE TABLE FARMACIE_DETALII(
	FarmacieId INT PRIMARY KEY IDENTITY(1,1),
	Nume NVARCHAR(50),
	Locatie NVARCHAR(100)
);
GO


CREATE TABLE MEDICAMENTE(
	MedicamentId INT PRIMARY KEY IDENTITY(1,1),
	Nume VARCHAR(50),
	Descriere NVARCHAR (500),
	Pret FLOAT,
	Stoc INT,
	FarmacieId INT,
	FOREIGN KEY (FarmacieId) REFERENCES FARMACIE_DETALII(FarmacieId)
);
GO

CREATE TABLE CUMPARATORI(
	CumparatorId INT PRIMARY KEY IDENTITY(1,1),
	Nume NVARCHAR(50),
	Data_Nasterii DATE
);
GO

CREATE TABLE CATEGORIE(
	CategorieId INT PRIMARY KEY IDENTITY(1,1),
	NumeCategorie VARCHAR(100)
);
GO


CREATE TABLE MEDS_CATEGORIE(
	MedicamentId INT,
	CategorieId INT,
	PRIMARY KEY (MedicamentId, CategorieId),
	FOREIGN KEY (MedicamentId) REFERENCES MEDICAMENTE(MedicamentId),
	FOREIGN KEY (CategorieId) REFERENCES CATEGORIE(CategorieId)
); 
GO

CREATE TABLE ANGAJATI(
	AngajatId INT PRIMARY KEY IDENTITY(1,1),
	Nume NVARCHAR(50),
	Pozitie VARCHAR(100),
	Email NVARCHAR(200), CHECK (CHARINDEX('@', EMAIL) > 0),
	FarmacieId INT,
	FOREIGN KEY (FarmacieId) REFERENCES FARMACIE_DETALII(FarmacieId)
);
GO

CREATE TABLE TRANZACTIE(
	TranzactieId INT PRIMARY KEY IDENTITY(1,1),
	NumeMed NVARCHAR(50),
	Cantitate INT,
	DataTranzactie DATE,
	CumparatorId INT,
	FOREIGN KEY (CumparatorId) REFERENCES CUMPARATORI(CumparatorId)
);
GO

CREATE TABLE MEDICAMENTE_TRANZACTII(
	MedicamentId INT,
	TranzactieId INT,
	PretTotal DECIMAL(10,2),
	Cantitate INT, CHECK (Cantitate BETWEEN 1 AND 10),
	PRIMARY KEY (MedicamentId, TranzactieId),
	FOREIGN KEY (MedicamentId) REFERENCES MEDICAMENTE(MedicamentId),
	FOREIGN KEY (TranzactieId) REFERENCES Tranzactie(TranzactieId)
);
GO

CREATE TABLE FURNIZORI(
	FurnizoriId INT PRIMARY KEY IDENTITY(1,1),
	Nume NVARCHAR(50),
	Adresa NVARCHAR(100)
);
GO

CREATE TABLE FURNIZORI_MEDICAMENTE(
	FurnizoriId INT,
	MedicamentId INT,
	PRIMARY KEY (FurnizoriId, MedicamentId),
	FOREIGN KEY (FurnizoriId) REFERENCES FURNIZORI(FurnizoriId),
	FOREIGN KEY (MedicamentId) REFERENCES MEDICAMENTE(MedicamentId)
);
GO
