CREATE DATABASE LAB5_FARMACIE
GO

USE LAB5_FARMACIE
GO

DROP TABLE IF EXISTS FURNIZORI_MEDICAMENTE;
DROP TABLE IF EXISTS MEDICAMENTE_TRANZACTII;
DROP TABLE IF EXISTS MEDS_CATEGORIE;
DROP TABLE IF EXISTS ANGAJATI;
DROP TABLE IF EXISTS TRANZACTIE;
DROP TABLE IF EXISTS MEDICAMENTE;
DROP TABLE IF EXISTS FURNIZORI;
DROP TABLE IF EXISTS CATEGORIE;
DROP TABLE IF EXISTS CUMPARATORI;
DROP TABLE IF EXISTS FARMACIE_DETALII;

IF OBJECT_ID('FARMACIE_DETALII', 'U') IS NULL
BEGIN
CREATE TABLE FARMACIE_DETALII(
	FarmacieId INT PRIMARY KEY IDENTITY(1,1),
	Nume NVARCHAR(50) NOT NULL,
	Locatie NVARCHAR(100) NOT NULL
);
END
ELSE
BEGIN
	PRINT 'TABELUL EXISTA DEJA!';
END
GO



IF OBJECT_ID('MEDICAMENTE', 'U') IS NULL
BEGIN
CREATE TABLE MEDICAMENTE(
	MedicamentId INT PRIMARY KEY IDENTITY(1,1),
	Nume VARCHAR(50) NOT NULL,
	Descriere NVARCHAR(500) NOT NULL,
	Pret FLOAT NOT NULL CHECK (Pret > 0),
	Stoc INT NOT NULL,
	FarmacieId INT NOT NULL,
	FOREIGN KEY (FarmacieId) REFERENCES FARMACIE_DETALII(FarmacieId)
);
END
ELSE
BEGIN
	PRINT 'TABEUL EXISTA DEJA!';
END
GO

IF OBJECT_ID('CUMPARATORI', 'U') IS NULL
BEGIN
CREATE TABLE CUMPARATORI(
	CumparatorId INT PRIMARY KEY IDENTITY(1,1),
	Nume NVARCHAR(50) NOT NULL,
	Data_Nasterii DATE NOT NULL
);
END
ELSE
	PRINT 'CUMPARATORI EXISTA DEJA!';
GO

IF OBJECT_ID ('CATEGORIE', 'U') IS NULL
BEGIN
CREATE TABLE CATEGORIE(
	CategorieId INT PRIMARY KEY IDENTITY(1,1),
	NumeCategorie VARCHAR(100) NOT NULL
);
END
ELSE
BEGIN
	PRINT 'CATEGORIE EXSITA DEJA!'
END
GO


IF OBJECT_ID('MEDS_CATEGORIE', 'U') IS NULL
BEGIN
CREATE TABLE MEDS_CATEGORIE(
	MedicamentId INT NOT NULL,
	CategorieId INT NOT NULL,
	PRIMARY KEY (MedicamentId, CategorieId),
	FOREIGN KEY (MedicamentId) REFERENCES MEDICAMENTE(MedicamentId),
	FOREIGN KEY (CategorieId) REFERENCES CATEGORIE(CategorieId)
); 
END
ELSE BEGIN 
	PRINT 'MEDS_CATEGORIE EXSITA DEJA';
END
GO

IF OBJECT_ID('ANGAJATI', 'U') IS NULL
BEGIN
CREATE TABLE ANGAJATI(
	AngajatId INT PRIMARY KEY IDENTITY(1,1),
	Nume NVARCHAR(50) NOT NULL,
	Pozitie VARCHAR(100) NOT NULL,
	Email NVARCHAR(200) NOT NULL, CHECK (CHARINDEX('@', EMAIL) > 0),
	FarmacieId INT NOT NULL,
	FOREIGN KEY (FarmacieId) REFERENCES FARMACIE_DETALII(FarmacieId)
);
END
ELSE
BEGIN
	PRINT 'ANGAJATI EXISTA DEJA!';
END
GO

IF OBJECT_ID('TRANZACTIE', 'U') IS NULL
BEGIN
CREATE TABLE TRANZACTIE(
	TranzactieId INT PRIMARY KEY IDENTITY(1,1),
	NumeMed NVARCHAR(50) NOT NULL,
	Cantitate INT NOT NULL,
	CHECK (Cantitate > 0),
	DataTranzactie DATE NOT NULL,
	CumparatorId INT NOT NULL,
	FOREIGN KEY (CumparatorId) REFERENCES CUMPARATORI(CumparatorId)
);
END
ELSE
	PRINT 'TRANZACTIE EXISTA DEJA!';
GO

IF OBJECT_ID('MEDICAMENTE_TRANZACTII', 'U') IS NULL
BEGIN
CREATE TABLE MEDICAMENTE_TRANZACTII(
	MedicamentId INT NOT NULL,
	TranzactieId INT NOT NULL,
	PretTotal DECIMAL(10,2),
	Cantitate INT NOT NULL, CHECK (Cantitate BETWEEN 1 AND 10),
	PRIMARY KEY (MedicamentId, TranzactieId),
	FOREIGN KEY (MedicamentId) REFERENCES MEDICAMENTE(MedicamentId),
	FOREIGN KEY (TranzactieId) REFERENCES Tranzactie(TranzactieId)
);
END
ELSE
BEGIN
	PRINT 'MEDIACEMNTE_TRANZACTII EXISTA DEJA!';
END
GO


IF OBJECT_ID('FURNIZORI', 'U') IS NULL
BEGIN
CREATE TABLE FURNIZORI(
	FurnizoriId INT PRIMARY KEY IDENTITY(1,1),
	Nume NVARCHAR(50) NOT NULL,
	Adresa NVARCHAR(100) NOT NULL
);
END
ELSE
BEGIN
	PRINT 'FURNIZORI EXISTA DEJA!';
END
GO

IF OBJECT_ID ('FURNIZORI_MEDIACMENTE', 'U') IS NULL
BEGIN
CREATE TABLE FURNIZORI_MEDICAMENTE(
	FurnizoriId INT NOT NULL,
	MedicamentId INT NOT NULL,
	PRIMARY KEY (FurnizoriId, MedicamentId),
	FOREIGN KEY (FurnizoriId) REFERENCES FURNIZORI(FurnizoriId),
	FOREIGN KEY (MedicamentId) REFERENCES MEDICAMENTE(MedicamentId)
);
END
ELSE
BEGIN
	PRINT 'FURNIZORI_MEDIACMENTE EXSITA DEJA!';
END
GO




